import { mount } from 'svelte';
import '@fontsource-variable/inter';
import '@fontsource-variable/source-sans-3';
import '@fontsource-variable/source-sans-3/wght-italic.css';
import '@fontsource-variable/source-serif-4';
import '@fontsource-variable/source-serif-4/wght-italic.css';
import '@fontsource-variable/lora';
import '@fontsource-variable/lora/wght-italic.css';
import '@fontsource-variable/stix-two-text';
import '@fontsource-variable/stix-two-text/wght-italic.css';
import '@fontsource/libertinus-serif/400.css';
import '@fontsource/libertinus-serif/400-italic.css';
import '@fontsource/libertinus-serif/600.css';
import '@fontsource/libertinus-serif/600-italic.css';
import '@fontsource/libertinus-serif/700.css';
import '@fontsource/libertinus-serif/700-italic.css';
import './style.css';
import './refinements.css';
import App from './App.svelte';
mount(App, { target: document.getElementById('app')! });
